### ISSUE TITLE
Should the ECG cable inside the scanning room get away from the MRI perpendicularly?

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#117]
See the conversation started at https://github.com/TheAxonLab/hcph-sops/pull/116/files#r1307960763

**Comment by celprov** [comment]
And should we tape the cables to the floor?

**Comment by oesteban** [comment]
> And should we tape the cables to the floor?

What's the point against taping them for the length of the session?

I'm way more concerned about whether there is any good in setting them in a particular arrangement. Let's figure that out first and then whether taping or other ideas for securing the position.

**Comment by esavary** [comment]
Hi! I remember that, too. I think the idea was essentially to avoid loops and cables getting in the way when moving the bed inside the bore. So I agree it is a good idea to tape the cables onto the bed. However, I'm not entirely convinced about taping the cables on the floor. If we decide to tape the cables on the floor, we should do it loosely to avoid breakage while moving the bed in and out.

**Comment by oesteban** [comment]
I'm not crazy then. Avoiding loops makes a lot of sense for the ECG (electrical) cable. Sure, whatever is taped should be done anticipating that the bed can move. One solution is to tape ONLY after the subject is already inside the bore.
