### ISSUE TITLE
Secret variable names showing computer name in preliminary.md and pre-session.md

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#122]
The secret variables should probably be updated with names that do not display the name of the computer (psychopy computer in this case).

Example line 198 of `preliminary.md`:
` *{{ secrets.login.username_hos68752| default("███") }}* and password *{{ secrets.login.password_hos68752| default("███") }}*`

I was suggesting to update to `username_psychopy` and `password_psychopy`.

**Comment by oesteban** [comment]
Thanks for finding this leak :)
