### ISSUE TITLE
New Dropbox Folder on Paid Account

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#123]
Our Dropbox folder has reached its storage limit, preventing us from uploading new files and data. To resolve this, we need to create a new folder on a paid account to store our data.

**Comment by celprov** [comment]
@esavary @oesteban An altenative may be to move to [Microsoft Onedrive](https://www.unil.ch/ci/onedrive) which is the service endorsed by UNIL

**Comment by oesteban** [comment]
Done

**Comment by esavary** [comment]
I cannot access the folder due to insufficient Dropbox storage capacity. Do you have the same issue, @celprov?

**Comment by esavary** [comment]
Hi! For a easy fix to the Dropbox issue, we could switch to view-only access for the folder. This would allow us to download files when necessary without taking up space on our account. However, it would involve setting up your account on the PsychoPy laptop. WDYT @oesteban ?

**Comment by celprov** [comment]
> I cannot access the folder due to insufficient Dropbox storage capacity. Do you have the same issue, @celprov?

@esavary Yes same issue.

**Comment by oesteban** [comment]
I can make it read-only.

**Comment by oesteban** [comment]
Okay, both of you are now view-only - can you access it?

**Comment by esavary** [comment]
Yes

**Comment by celprov** [comment]
Yes I can access it, and it seems I can download its content

**Comment by oesteban** [comment]
I think we can close this for now.
