### ISSUE TITLE
Update SOPs with O2 concentration recording

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#129]
We are about to receive the new cable...

**Comment by celprov** [comment]
Seeing [the flowchart about experimental settings](https://github.com/TheAxonLab/hcph-sops/blob/6b017f0592b09b9845af5dd48a20b6be71fc7814/docs/data-collection/intro.md?plain=1#L6), I was surprised to see an arrow 'Channel 4 O2'. So it is true we are gonna measure O2 as well @oesteban ?

PS we would also need then to update the [main project image](https://github.com/TheAxonLab/hcph-sops/blob/6b017f0592b09b9845af5dd48a20b6be71fc7814/docs/assets/images/cohort1.png)

**Comment by oesteban** [comment]
Yes it is, if the purchase of the cable finally goes through.
