### ISSUE TITLE
"Command 'mkdocs' not found" after following the installation instructions

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#130]
I tried to run/build the website locally. All steps went well until `mkdocs serve` which output:

```
Command 'mkdocs' not found, but can be installed with:
    sudo apt install mkdocs
```

The `python -m pip install -r requirements.txt` did raise some warning that the installed packages were not added to the path but adding the install directory to the path did not solve the issue.

However, running `python -m mkdocs serve` works - could this be an issue with multiple installations/versions of python ?

**Comment by oesteban** [comment]
Yup this totally looks like your python distribution is not on the PATH.

```
python -m mkdocs serve
```
doesn't look like a bad workaround :)

**Comment by acionca** [comment]
Adding the correct path to the PATH solved the issue (in my case `$HOME/.local/bin`).
