### ISSUE TITLE
"above" or "below" statements not referring to anything on the actual page

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#135]
There are "above" or "below" statements that appear to not be referring to anything (usually because something has been moved to another page). Is this for compatibility with the _pdf_ version ? Should the references be updated ?

Here's an example from `preliminary.md` after "Install the BIOPAC" where there are no reference to the BIOPAC before on the page:

> Make sure you understand the components and settings of the BIOPAC, described **above**.

**Comment by oesteban** [comment]
Good catch, I introduced this problem yesterday when splitting the intro into a new file. Will fix
