### ISSUE TITLE
Add instructions for a safety check of the desiccant chamber in pre-session.md

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#136]
I would suggest to add an "important" admonition to ensure that the operater does a safety check of the quality of the desiccant chamber silica beads (making sure they are not pink).

It could be in "Setting up the BIOPAC system and physiological recording sensors", right after :
> Go back to the control room and connect the proximal end of the cannula extension tube to one plug of the desiccant chamber (which one is not important). Connect the MLA0110 inline filter to the other plug of the desiccant chamber. Connect the MLA0343 drying tube to the MLA0110 inline filter.

**Comment by oesteban** [comment]
Yesterday night I pushed an update in the new intro: https://www.axonlab.org/hcph-sops/data-collection/intro/

If you go all the way down, there are two folded tabs, one for the BIOPAC and one for the GA. If you expand the GA, you'll see a warning there about this. Would that suffice?

**Comment by acionca** [comment]
Yes, but the warnings currently are in [Getting familiar with the instruments](https://www.axonlab.org/hcph-sops/data-collection/intro/#getting-familiar-with-the-instruments) within the overall description of the experimental setting. If you believe the dessicant chamber has any chance of turning pink during the project, I think it could be safe to repeat/remind that in the [pre-session](https://www.axonlab.org/hcph-sops/data-collection/pre-session/) checklist.
