### ISSUE TITLE
Adding pictures of the positioning and alignment of the ET

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#141]
In the [inside the scanner room](https://www.axonlab.org/hcph-sops/data-collection/pre-session/#inside-the-scanner-room) section, there are instruction for repeatable positioning of the ET and to align the ET arm to scotch tapes. 

> - Place the plexiglass standing panel inside the scanner bore: a sign notes the top side that faces up. The plastic feet must face down to avoid the panel to slide. To ensure the repeatible positioning of the ET, place the end of the plexiglass such that its edge aligns with the edge of the illuminated MRI rails.
> - Place the ET arm on top of the plexiglass panel with the two posterior feet of the ET arm aligned within the two corner signs made of scotch tape.

I think it is difficult to imagine the positioning without being there and that pictures showing the positioning and alignements could improve clarity (maybe one picture for the position of the ET arm and one showing what should be aligned with what).

**Comment by esavary** [comment]
It'd be really helpful, but I'm not sure we can take pictures inside the scanning room (no phones allowed there). But maybe we could take pictures on a table outside the room to illustrate the positioning on the plexiglas ?

**Comment by oesteban** [comment]
> It'd be really helpful, but I'm not sure we can take pictures inside the scanning room (no phones allowed there). But maybe we could take pictures on a table outside the room to illustrate the positioning on the plexiglas ?

Yup

**Comment by oesteban** [comment]
While I agree this would be interesting, I think there's nothing very special that cannot be shown to someone new and/or extracted from the ET's manual. I'm closing to focus attention on other more pressing issues. Please reopen if you still want to do it, it would be a good addition though.
