### ISSUE TITLE
Date of birth of the operator is shown in multiple pictures in preliminary.md

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#142]
I am not sure the date is correct but it appears that almost all pictures of the MRI console in [setting up the scanner protocol at the mr console](https://www.axonlab.org/hcph-sops/data-collection/preliminary/#setting-up-the-scanner-protocol-at-the-mr-console) are displaying the date of birth of the operator. Is supposed to be sensitive ?

**Comment by oesteban** [comment]
You mean the participant's DOB, right (i.e., it's mine :D)

**Comment by acionca** [comment]
Yup, are you ok with it being displayed ?

**Comment by oesteban** [comment]
Yup, I was aware of it being there.
