### ISSUE TITLE
Commits from forks do not appear in CircleCi

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#159]

**Comment by esavary** [comment]
@oesteban  , I've enabled 'Build forked pull requests' in the project parameters to fix the issue. Is this okay with you? If you didn't selected this option intentionally, I can undo the change.

**Comment by oesteban** [comment]
Thanks!

**Comment by esavary** [comment]
It fixed the problem, but we must be careful not to track the project's fork in our CircleCI. Otherwise, the commit will appear in our account but not the project's account.
