### ISSUE TITLE
Flow chart of the post-scanner steps

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#160]
- Mostly to summarize the processing steps as well as the transfer of data

**Comment by acionca** [comment]
Not sure how to properly share this but below is a work in progress (editable [here](https://mermaid.live/edit#pako:eNqNVlGP4jYQ_ituKtRWgl0Id8tBpUpcUnqIUu4I24eGCnljA-4mdpo4x9HN_veObRISwq6WhzD2fDOe-TKeyZMVCEKtkbUNxSHY40Si1cc1R_ALQpymLt0iFsUolYl4pKPvt91u28idAyNyP7Ljbz-vubFIs4ddguM9-jx2PF89_jYKykkDE--PKRO--QvFjgU4RIGI4kzS5BW7UABwQ7DEvnpAZCLBO3qyUL8EHzZRwvwlPqD5cnqhUQdqlRIqugdGUm32cep6F3Zapw21smKpI1TCRZQqtBAT34X_3zG5cs6mgFw5r9UqT6zDLmIGN_8GG5FJ_0-WZsBfQmORyCokhq1EBJstnOB_NguappSgbf3MAkgaQGKA1fAiITcB5alI_LmQTHBkVk23rVZCd4l25LuUC5Zew2xZCG8dIJOTcAmZOPUAiAQCH5nvrqYIc4LcWd0hObCNIFt_4U6AlEBwKNoskJTUUDLBgfRX6lnlTDlXpE7GbTR3b8fu7dLVp8xnt-PZ7XJWwXrO64UgYso5zRLhL0BCfyixYp7xkmf__iwjVTcplbX3U-BqL6cJhGQ5DST7yuTR95w2cNe8Tq3WWyJstRpFven5cxZSuHWcIruGe3s-Bl9Sdu0Yu3JMv2b2JiIM9GUqGhFUuFGNC3U6v-QxDtIIc5QGCYtlXjQWgzKNC3CdfLVAk-lv98tf0eJ-lZddploPJ1Pt9hPNCHME_1o6LnrCGavsTQwg2EpfBxv_Bl9Ya_xkuvRWKAVO1K0UPDyi73IUAVtOyLhusuCIUs747sQFKLXp2prygBHKoeH8mP60tnKEQ5pIf6yeKIbhwAIWY16QrCeEwaghUcRz7tDabZBAIP-Ihxx9WiT3J1a0qNRFp6ynUnQ97QA6wRcnf63ZnfIoANrqyw8zfNRWG9g1OfveZepVrTFzUsSFROIxR0uaBntKspBW8z3vVpO-GrlqYqpI87e14as-SMPHix36XG5XPcVHQrc4oGUlVS5rcQ1qHNYBp7KvBKExFy6qiV7qy6unlTGLKZQkLXYvLDvoPGTK6ModDSgnS6EvN7S6GCqFtjFTr6KKtQ5-4lzNCsg0swwqKa_MJkiNvJYaKVI7ja9Cf1qa-2CGz1W21bnngZefsQZ9Wr5EezMKMyTLKMxSq_RkLBR6ob16zktxOZ4ZkRordCOH2-eV1HiOdlDtyEYxaSqsthXRJMKMwIfpk4KtLbmnEV1bIxBVFWehXFtr_gxQnEnhHXlgjWDE07aVxfB6qcswBBFZoy0OU9ilhMGH4tx87Opv3rYFrewvIc4YWFujJ-ubNerf2B_s3t1g2Ovaw2H3w6BtHa2R3R3e2IP3drdn3_V7_Xf9_nPb-k976N10ze99793gbtAf9p__Bwkhqlw)):

![image](https://github.com/TheAxonLab/hcph-sops/assets/43985138/ba0afd8e-0a1d-4854-9db4-848ff281e575)

All comments are more than welcome @oesteban @esavary @celprov

**Comment by esavary** [comment]
Looks great! In the future, we will have to add an additional path in the scheme for Eye-tracking data.

**Comment by oesteban** [comment]
@acionca - why don't you create a PR to add this as a starting point?
