### ISSUE TITLE
Link reference issue in post-session.md

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#161]
The link to "convert the data into BIDS" seems to be pointing to `#convert-data-to-bids-with-heudiconv-and-phys2bids` instead of `#convert-data-to-bids-with-heudiconv`.
> To do so, you'll need to first [download the data from PACS](https://www.axonlab.org/hcph-sops/data-management/post-session/#download-the-data-from-the-pacs-with-pacsman-only-authorized-users) and then [convert the data into BIDS](https://www.axonlab.org/hcph-sops/data-management/post-session/#convert-data-to-bids-with-heudiconv-and-phys2bids) as indicated below.

Further, the instructions are missing.

**Comment by oesteban** [comment]
I think alex is commenting that the links are broken, correct? (in addition to the fact that we need to write the section...

**Comment by acionca** [comment]
Yes, exactly
