### ISSUE TITLE
Post-session retrieval instruction may be unclear

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#163]
It is written that we should
> Send the T1-weighted and T2-weighted scan for screening and incidental findings.

within 48 hours after the first session and that

> To do so, we'll need to first download the data from PACS and then convert the data into BIDS.

However these last two instructions are to be done within one week and two week after the completed session.

Does it implies that, for the first session only, we should have everything in BIDS format, sent for screening within the first 48h ?

**Comment by oesteban** [comment]
> Does it implies that, for the first session only, we should have everything in BIDS format, sent for screening within the first 48h ?

Yes

**Comment by oesteban** [comment]
Please reopen if you still think this is unclear.
