### ISSUE TITLE
Output Calibration Data

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#175]
The calibration information is currently missing from the EDF file output. We need to output the calibration data either from the PsychoPy code or directly from the ET computer.

**Comment by oesteban** [comment]
What's the status of this?

**Comment by esavary** [comment]
We check if the validation is 'Good,' and if it's 'Fair' or 'Failed,' we restart the calibration. One option could be to take screenshots of the values, but aside from that, we don't have a quick solution

**Comment by oesteban** [comment]
As discussed today, for the "header" of the EDF file, we will store it as a list of strings (one string per line) in the JSON file. This will be done in addition to saving the calibration parameters following the eyetracking BEP.
