### ISSUE TITLE
[Protocol] Find a T2w sequence that is not FLAIR

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#179]
I believe FreeSurfer will work better with a T2w image with more T2 contrast.

WDYT @yasseraleman ?

cc/ @helenelajous

**Comment by yasseraleman** [comment]
I think the same Oscar.

**Comment by helenelajous** [comment]
@oesteban What will the T2w images be used for? improving FreeSurfer's brain segmentation from the T1w images? improving skull-stripping?

From the literature, it seems that T2w images are indeed preferred compared to FLAIR. What would be the requirements for an alternative T2w sequence? Strong T2 contrast, high spatial resolution (we are currently at 0.5×0.5×0.9 mm3) in a reasonable acquisition time (~5 minutes)?
Could a T2-SPACE be a good alternative to FLAIR? Or simply a conventional fast spin echo sequence?

**Comment by oesteban** [comment]
> Strong T2 contrast, high spatial resolution (we are currently at 0.5×0.5×0.9 mm3) in a reasonable acquisition time (~5 minutes)?

This would be perfect.



> Could a T2-SPACE be a good alternative to FLAIR?

I believe we are already acquiring T2-SPACE, so it might be just changing some parameters. If I'm wrong, sure, T2-SPACE is the most straightforward option.

**Comment by helenelajous** [comment]
We are currently acquiring a T2-FLAIR, not a T2-SPACE. If I understood correctly, you want an alternative to the FLAIR, don't you?
I cannot find any recommendation from the literature, but we could try either a conventional FSE or a T2-SPACE.

**Comment by oesteban** [comment]
@helenelajous you are totally right, we are not acquiring a T2w sequence at all and it cannot be SPACE (or modification thereof) because SPACE is a TSE (https://www.siemens-healthineers.com/magnetic-resonance-imaging/options-and-upgrades/clinical-applications/syngo-space).

As per this document (https://www.center-tbi.eu/files/project/Neuroimage%20sequences%20summary_CENTER-TBI_Siemens.pdf) - SPCIR is indeed a FLAIR sequence.

**Comment by helenelajous** [comment]
Let's try a T2-SPACE or common FSE sequence then and see if the contrast suits us better - this way, we will probably also decrease the acquisition time!

**Comment by oesteban** [comment]
Okay, the one we acquired on Monday looks pretty good. Next time we need to figure out how to reduce the time (currently over 6 minutes). I think we can try to trim down voxels in SI/IS encoding direction.

**Comment by helenelajous** [comment]
You could also try to reduce the TR if possible - but check the contrast.
