### ISSUE TITLE
Where should we put the instruction for the computation of connectivity matrices ?

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#183]
I was thinking about adding a set of pages right after _Preprocessing_ that could be named _Connectivity_ (containing pages such as `Connectivity/Functional` and `Connectivity/Structural`) - got any idea/suggestion on that ?

**Comment by oesteban** [comment]
Why not *inside* preprocessing?

Preprocessing
       - fMRIPrep & dMRIPrep
       - Extracting structural connectivity
       - Extracting functional connectivity
