### ISSUE TITLE
Automatically convert ET to BIDS after a task is finished

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#185]
Perhaps using TheAxonLab/HCPh-fMRI-tasks#27 as a test bed, we would run the conversion to BIDS at the end of the psychopy experiment as "custom" code.

**Comment by esavary** [comment]
I'm not entirely convinced it's a good idea to integrate the conversion to BIDS directly into the Psychopy experiment as custom code block. Is there a specific reason for doing it within the Psychopy code? I'm a bit concerned that this might increase the risk of the Psychopy experiment crashing. Perhaps it would be better to run this as a separate script and explore automation when a new EDF file is saved, if needed?

**Comment by oesteban** [comment]
> Perhaps it would be better to run this as a separate script and explore automation when a new EDF file is saved, if needed?

This is definitely the better option. I would very much prefer this option for exactly the reasons you mention 👍

**Comment by oesteban** [comment]
I'm going to close this for the time being. It doesn't feel like it makes a lot of sense as we are past the midpoint of the acquisition.
