### ISSUE TITLE
DWI: report the small delta/capital delta

### ISSUE THREAD

**Issue by helenelajous** [TheAxonLab/hcph-sops#187]
Related to #181, once we have the final, clean research protocol, we should keep track of the small delta/capital delta (they are not saved in the protocol itself, but we can read them at the scanner).

**Comment by oesteban** [comment]
Yes, I had forgotten about this and indeed, it is very important.

**Comment by helenelajous** [comment]
In our current protocol (I refer here to the piloting session on July 14th):
delta=19.4 ms
DELTA=42.6 ms
To double-check if we change to Ines' DWI sequence

**Comment by oesteban** [comment]
You can use latex on GitHub :)

$\delta$ = 19.4 ms
$\Delta$ = 42.6 ms

(which was created with the following markdown text)
```
$\delta$ = 19.4 ms
$\Delta$ = 42.6 ms
```

BTW, these I suspect will change if we change the TR of the DWI.

**Comment by oesteban** [comment]
@acionca @esavary let's not forget to write these down for today's protocol (and keep doing it until we have the four of them written down).

**Comment by acionca** [comment]
Here are the deltas measured during session 17:
AP: $\delta$ = 23.3ms and $\Delta$ = 47.5ms
PA: $\delta$ = 23.3ms and $\Delta$ = 47.5ms
LR: $\delta$ = 27.2ms and $\Delta$ = 46.9ms
RL: $\delta$ = 27.2ms and $\Delta$ = 46.9ms

**Comment by oesteban** [comment]
Pinning this for when I consolidate metadata in BIDS -- thanks @acionca and @helenelajous !
