### ISSUE TITLE
Automatically launch preprocessing

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#189]
To make our life easier (especially because we are a small team that's gonna have to do a lot of data processing),
would it be possible to launch the preprocessing automatically once the data were pulled out of the PACs?

First launching automatically heudiconv for BIDS conversion and then from the BIDS dataset, automatically launching at least MRIQC, fMRIPrep and dMRIPrep.

Our colleagues here are using Flywheel to do so.

**Comment by oesteban** [comment]
> To make our life easier (especially because we are a small team that's gonna have to do a lot of data processing), would it be possible to launch the preprocessing automatically once the data were pulled out of the PACs?

PACS fetching is automatic with a cron job. I can update the SOPs with that.

> First launching automatically heudiconv for BIDS conversion and then from the BIDS dataset, automatically launching at least MRIQC, fMRIPrep and dMRIPrep.

I could automate heudiconv, but I prefer to make it manually. I have added a few bash scripts to the SOPs with semi-automations and that is sufficient to get things going.

The main caveat is when to trigger heudiconv - assume the session has been downloaded? There's some practical details (e.g., picking the right session's folder) that are just more work to automate than running it every morning manually as I'm doing.

RE: MRIQC, I think at this point it doesn't make much sense to automate :(

Re: fMRIPrep / dMRIPrep: cannot be automated.

Please reopen if you feel there's something I haven't addressed and you think we need to change/improve.
