### ISSUE TITLE
[Protocol]  Ensure the task starts on time (fMRI, breath-holding task)

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#196]
They started at 8/207 on July 14th, 2023 (from https://github.com/TheAxonLab/hcph-sops/issues/181#issuecomment-1719762301).

**Comment by oesteban** [comment]
@helenelajous - what do you mean by "recordings"? is it the physiological recordings (i.e., BIOPAC)?

**Comment by helenelajous** [comment]
I meant that the task didn't start right after the dummy scans - sorry for the misunderstanding.

**Comment by oesteban** [comment]
Thanks! edited the title.

**Comment by esavary** [comment]
Last time we checked, it finished on time, so I'm closing the issue (Feel free to reopen if needed).
