### ISSUE TITLE
[Protocol] Consolidate four protocols for the four possible PEs

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#198]
Store the protocols as they will be executed during the collection phase.

This should address #38 (I leave that one open for the documentation aspect of it, to remind us of updating the SOPs)

**Comment by helenelajous** [comment]
Because of the warning against "exceeded stimulation limits" when changing the PE direction from AP/PA to LR/RL, make sure that the gradient mode of each sequence in every of the final four protocols allows us to run the same whole protocol from one session to the other.

**Comment by oesteban** [comment]
I have created four protocols:

- HCPh_PA
- HCPh_AP
- HCPh_LR
- HCPh_RL

We will try to figure out the stimulation problem, but today we were unable to fix it.

However, there's some ray of light. JB today suggested we reduce the Phase FoV of the dwi - We then should copy the dwi on the old sequence (not to generate triggers, although I'm tempted to generate triggers and have more info to debug the triggers on calibration).

The functional should be alright.

**Comment by oesteban** [comment]
Let's reopen this issue if the exceeded stimulation limits appears again.
