### ISSUE TITLE
Generate the `_events.tsv` files for all acquired piloting sessions with fMRI

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#199]
Right after I generate the first datalad version of the dataset

**Comment by celprov** [comment]
@oesteban is this a problem we need to solve before the data collection?

**Comment by oesteban** [comment]
I think so. Having task files without events is a really risky business.

**Comment by celprov** [comment]
@esavary @oesteban I can help with this. 
I'm gonna meet with Sunjae (a colleague here) tomorrow, to get a sense of how to do this. Because right now, I have zero clue.
Btw this '_events.tsv' should be extracted from the psychopy tasks right? not the physiological signal (that's why I removed the physio label).

**Comment by esavary** [comment]
For the most recent sessions, I've been working on debugging a code to extract data from the triggers recorded in the physiological data. For sessions where we were either sending messages to the Eye Tracker (ET) without triggers or had missing trigger data in the physiological records, I can manually write the file using the messages outputted by the ET.
However, the challenge lies in the first sessions, where we lack both ET messages and triggers. In such cases, extracting events from the physiopy logs for those sessions might be possible. However, the logs are somewhat cryptic, and the documentation is limited.
If he is familiar with interpreting these logs, that would be very helpful.

**Comment by celprov** [comment]
Let me describe here precisely what we want for the `events.tsv` file and how I think we can find those info from the psychopy log:

- **Resting-state**: we want to events file to contain two values: 

    - onset = when the movie starts
         The movie onset corresponds to the `EXP 	movie: autoDraw = True` event in the psychopy log. It can also be found in the `resting-state*.csv` under the field `movie.started`.
    - duration = 1200s because we have set the movie to last 1200s
        And indeed if you compute the time difference between `EXP movie: autoDraw = False` and `EXP movie: autoDraw = True`, it corresponds to 1200s.

- **Qct**: we want one line per instance of sub-task. The sub-tasks are:
     - **blank** : it is fully characterized by its onset and its duration. Only one line in the event.tsv is needed.
     - **motor**: onset, duration, trial_type= motor, value = {LEFT or RIGHT}
                        The motor sub-task generates two lines in the `events.tsv`, one for fingertapping with the left hand, and one with the right hand.
     - **cognitive**: on top of its onset and its duration, an instance of the cognitive task needs the position of the ET point to be fully characterized. (that we can encode in the field `value` of the `events.tsv` as  '[0.5, 0.6]' or as 'xpos=0.5, ypos=0.6'.
          This means we enter a new line in the event file everytime the fixation point moves.
    - **visual**: the visual sub-task is characterized by a single event in the psychopy log, even if the grating changes direction. So I think for this task, we can also enter only one line in the `events.tsv`

- **Bht**: the instances we need to encode as one line in the `events.tsv` file for the bht task are:
    - breath in
    - breath in last
    - breath out
    - breath out last
    - hold
    - hold test
    
    
As a global comment, the onset of each instance is marked by {WORD SPECIFIC TO THE TASK} : autoDraw = True, and its end is marked as {WORD SPECIFIC TO THE TASK} : autoDraw = False. The fact that 'autoDraw' is the key word that determines onset and end of task instances is supported by the observation that its timing corresponds all the time to the field {WORD SPECIFIC TO THE TASK}.started and .stopped in the csv file.

**Comment by celprov** [comment]
Do we have to generate an event file for the new fixation_dwi and validation tasks?

**Comment by oesteban** [comment]
The fixation yes, but it has the issue of the calibration scans. The
validation no

**Comment by esavary** [comment]
It appears that psychopy-bids strongly recommends Python 3.8 for optimal compatibility and doesn't guarantee support for higher Python versions. I think our current environment on the Psychopy laptop is Python 3.10. What are your thoughts on downgrading to 3.8? Personally, I believe the potential benefits don't outweigh the risks of changing python version in the middle of the acquisitions. I think Céline's code can already parse events correctly.

**Comment by oesteban** [comment]
yeah, I was also looking at it and I'm not sure it's going to save us much time - let's drop the idea. Thanks a lot for looking into it.
