### ISSUE TITLE
Deactivate the triggers in field mapping

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#217]

**Comment by celprov** [comment]
@esavary is this needed before the data collection?

**Comment by esavary** [comment]
That would be the ideal scenario, but if we can't find a solution, I can work around the issue.

**Comment by oesteban** [comment]
Changing the label, otherwise we will not have this under the radar tomorrow.

**Comment by oesteban** [comment]
Closing as it is not possible to disable.
