### ISSUE TITLE
Parametrisation of the syncbox is missing in the SOPs

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#218]
The parameters we're using with the syncbox aren't documented in the SOPs. It would be good to include them to ensure uniformity across all sessions. This information is also essential for determining the number of triggers received by the BIOPAC, which is necessary for converting physiological data to BIDS.

**Comment by esavary** [comment]
@oesteban @celprov @helenelajous A related question: During the previous sessions, did we use specific parameters, or the ones already in Syncbox?

**Comment by esavary** [comment]
There is a picture in the SOPs with a part of the parameters, but it's not clear to me if it's what we used.

**Comment by oesteban** [comment]
> The parameters we're using with the syncbox aren't documented in the SOPs.

Totally agreed. And they should be documented. Thanks for catching this problem.

> A related question: During the previous sessions, did we use specific parameters, or the ones already in Syncbox?

I believe we just want to forward all triggers, correct? Relatedly, if the CMRR sequences allow it, we should maybe send triggers only with TRs (perhaps we are already doing this).

**Comment by esavary** [comment]
I'm still figuring out what's happening in the different sequences. I only know that the DWI sequence sends one trigger for each slice. I'm trying to understand from the data, but it would reduce the number of unknown variables to know the parameters of the syncbox we used during the last session.

**Comment by celprov** [comment]
@esavary I don't remember ever changing the parameters that were already on the syncbox

**Comment by oesteban** [comment]
I believe 'parametrization' here means 'configuration'. You can configure
the syncbox to forward all triggers or filter some in 'synchronization
mode'.

**Comment by celprov** [comment]
I labeled this item as urgent, because we need to make sure we use the correct Syncbox settings everytime.

**Comment by oesteban** [comment]
I think this is now fixed: https://www.axonlab.org/hcph-sops/data-collection/tear-up/#check-synchronization
