### ISSUE TITLE
Put together the mood questionnaire

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#221]
The idea is to collect information about mood, coffee, and medication intake (and probably other stuff that I forgot) in a Google form.

That Google form should also inform us which phase encoding direction should be acquired on that day (cf #38)

Russ also suggested that we add a quick screen for wakefulness/arousal.

**Comment by acionca** [comment]
I could ask my old team from neuropsychology in Geneva if they have templates or ideas of aspects that coul be quickly screened as well.

**Comment by oesteban** [comment]
Should also collect sleep information (not sure how different this is from wakefulness/arousal)

Should also collect body temperature, room temperature, blood pressure, weight.

**Comment by oesteban** [comment]
@acionca https://bmcneurosci.biomedcentral.com/articles/10.1186/s12868-017-0383-y/tables/2

**Comment by acionca** [comment]
I made an issue template for the questionnaire available [here](https://github.com/TheAxonLab/hcph-mood-quest). I believe detailed discussions around that topic could be centralised on the corresponding repo. Let me know what y'all think @oesteban @celprov @esavary
