### ISSUE TITLE
Gain basic understanding of what a good physio signal looks like

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#231]
@esavary @acionca do you have some basic notion about what a good ECG, a good respiration belt and a good CO2 signal look like?

We need a basic idea so that if the signal looks totally crap, the belt or the canula or the electrodes can be corrected before acquiring more data.

**Comment by oesteban** [comment]
Perhaps @smoia can point us to some fast resource from the physiopy community.

**Comment by smoia** [comment]
We don't have anything published yet, but we are plannign on creating a _gallery of horrors_ in our documentation. In the meantime, I can refer you to the Physiopy Slack, and to this beautiful slide that @cesarcaballerogaudes made for our physio EC in OHBM 2022 (note it's PPG, not ECG)
![Schermata da 2022-06-13 16-15-01](https://github.com/TheAxonLab/hcph-sops/assets/35300580/4a5aa896-2706-42f9-a3f2-152e114aafe0)

Also note that the respiration belt's issues shown here might be opposite if (a) you're attaching it to the wrong pole and (b) you are using the "butterfly" vs the pneumatic belt.

**Comment by celprov** [comment]
Thank you, @smoia and @CesarCaballeroGaudes (I remember that slide from when I attended the course last year :) )! 
Is this course openly available somewhere?

Do we have your permission to incorporate this slide into our SOP, with proper citation?

The third question concerns how to address the issue of 'CO2 recording with vacuum too low.' Is it related to the calibration of the gas analyzer?

Thirdly, do you have any ECG-related resources in mind? 
Drawing parallel from the other signals, it seems to me suitable criteria would be that the envelope and the period of the signal remain constant. 

I've begun outlining some Quality Assurance criteria based on this slide #243. Your feedback would be greatly appreciated.

**Comment by smoia** [comment]
@raystick @kristinazvolanek might know better - try to crank the CO2 gas analyser vent up as much as possible.

Your setup is ok, it's just that the scanner is fairly far from the console. Getting the shortest line of tubes possible (that still lays on the floor) helps. I have the suspicion that the drying box does not help with that problem - might be worth trying the drying tubes instead. @raystick @kristinazvolanek did you ever tried drying components in the cannulae lines, like the dessicant box or the drying tubes?

**Comment by celprov** [comment]
@smoia just to lift any misunderstanding. I think our physiological signal in general, look ok (none of the problem illustrated on the slide appear systematically as far as I remember). We just ask as a precaution, in case that happens, what should we do?

**Comment by smoia** [comment]
All of the above, plus send back the gas analyser for maintenance should you notice a drop in air suction.
