### ISSUE TITLE
Buy or find a barometer to have in the MR room

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#250]

**Comment by acionca** [comment]
I believe @esavary has found something for that - we'll test and close as soon as it's confirmed to be working.

**Comment by esavary** [comment]
Yes, we can test today. I just need 2 AA batteries (maybe we have this at the lab?)Le 19 oct. 2023 09:40, Alexandre Cionca ***@***.***> a écrit :
I believe @esavary has found something for that - we'll test and close as soon as it's confirmed to be working.
