### ISSUE TITLE
Investigate if there is a possibility to use the deamon in 'test mode' 

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#256]
@acionca :
For now it is possible to test the forward-trigger service using `sudo python forward-trigger-service.py --disable-mmbt-check` and see that everything is working well when pressing `s`. However, since we will have to use this specific flag to test without the MMBT box, I am not sure if it would work when using the daemon as explained in the latest appendix from #251. Especially, it is not working when modifying `/etc/systemd/system/forward-trigger.service` to:
``` shell
[Unit]
Description=Forward Trigger Service
After=network.target

[Service]
ExecStart=/usr/bin/python3 /path/to/forward-trigger.py --disable-mmbt-check
WorkingDirectory=/path/to/forward-trigger/directory
StandardOutput=null

[Install]
WantedBy=multi-user.target
```

**Comment by oesteban** [comment]
I'm not sure this has a lot of advantages over manually running:

```
sudo /usr/bin/python3 /path/to/forward-trigger.py --disable-mmbt-check
```

I'll close it -- please reopen if you feel I'm wrong in my assessment.
