### ISSUE TITLE
Are we acquiring the positive-control task at the right time ?

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#264]
From the previous piloting sessions, I believe we are acquiring the QCT task before the EPI BOLD field mapping. However, in the latest [scanning protocols](https://www.axonlab.org/hcph-sops/data-collection/intro/#scanning-protocols) from the SOPs, the QCT should be after the EPI BOLD. Should we update the SOPs to match the actual protocol ?

**Comment by oesteban** [comment]
Yes, please.
