### ISSUE TITLE
How precise do we need to be in the event onset and duration?

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#269]
Here is an extract of a psychopy log for the resting-state task: 

> 117.7445 	EXP 	fixation_out: autoDraw = False
> 117.7445 	EXP 	fixation_in: autoDraw = False
> 117.7445 	EXP 	text: autoDraw = True
> 158.2110 	DATA 	Keypress: s
> 158.2477 	EXP 	text: autoDraw = False
> 158.2477 	EXP 	movie: autoDraw = True
> 159.8242 	DATA 	Keypress: s

As you can see timestamps in the log are reported up to the 4th decimal.

We have coded the movie to start with the first trigger, that is when the fMRI data starts to be recorded. In that logic, the movie onset should be 0.0. However, you see there is a 0.0367s delay between the first trigger "Keypress: s" and the movie onset "movie: autoDraw = True".

(BTW you also see that the the time of the tasks does not correspond to the time of the fMRI collection (movie onset is 158.2477s in the task time vs 0.0 in fMRI time), so we have to subtract the time of the first trigger to all tasks onset to record when events happen in fMRI time.)

My reasoning is that we don't need to report this delay, because the time resolution of fMRI is anyway around 1s at best. 

**As such, I propose that we report all onsets and durations up to 1 decimal.**

The second reason for this choice is that for bht and qct and given that we do not have the trigger recorded for the early session, we have to approximate the time of "Keypress: s" with the nearest event which here is "text_2: autoDraw = False". So we are precise up to the first decimal but not beyond. This relates to #270 

> 6.5253 	EXP 	Created calibration_2TargetInner [...]
> 56.8751 	EXP 	text_2: autoDraw = True
> 96.1235 	DATA 	Keypress: s
> 96.1414 	EXP 	text_2: autoDraw = False
> 96.1414 	EXP 	directions: autoDraw = True

Let me know if you disagree.

**Comment by oesteban** [comment]
> (BTW you also see that the the time of the tasks does not correspond to the time of the fMRI collection (movie onset is 158.2477s in the task time vs 0.0 in fMRI time), so we have to subtract the time of the first trigger to all tasks onset to record when events happen in fMRI time.)

This is why phys2bids has "negative" timepoints. You set your "fMRI time" to be zero (as you suggest), and previous events are kept, but assigned negative timestamps. That way you are aware that they exist and can have them recorded, but facilitate analysis by setting the reference at the right point.

Re: decimal resolution - our TR is 1.6 sec. so I would say two or three decimals would be better in this case. there's always time to round things if necessary at analysis time.

**Comment by celprov** [comment]
We have decided to keep the same decimal level as physiopy and let the researchers decide if they should round it or not at analysis time.
