### ISSUE TITLE
Are all psychopy logs in the Dropbox?

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#270]
@esavary @oesteban The earliest real session (not tests made by elodie for implementing the tasks) of psychopy log that is present in the Dropbox is May 25th? 

Did we acquire physio before that?

I'm asking, because I understood that we had physiopy logs where we did not record the trigger yet, but that earliest session already has triggers recorded in it.

Related to #269

**Comment by oesteban** [comment]
@esavary ?

I personally don't remember, but it makes sense we may not have properly stored them before.

**Comment by esavary** [comment]
Yes, we have Psychopy data from earlier sessions, and I'll get them updated on Dropbox soon. However, it's worth noting that we haven't been collecting physiological data (except for sporadic Eye-tracking data) until May, when we started using the Biopack for the first time.

**Comment by oesteban** [comment]
@esavary, can this be closed? (meaning - have you uploaded them to Dropbox already and checked when's the first log we have?

Regardless of whether we collected physio, the psychopy logs are critical to generate the events files. Without events files, the task fMRI data are basically useless (and the QCT would be interesting to have even without physio).

**Comment by esavary** [comment]
Yes, I have uploaded the files on Dropbox, so I'm closing the issue. @celprov feel free to reopen if necessary.
