### ISSUE TITLE
Eye tracker configuration in psychopy

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#273]
In the parameters, we must select the type of eye-tracker: EYELINK 1000 LONG RANGE, TOWER, DESKTOP, or REMOTE. @bfranceschiello is correct to use LONG RANGE?

**Comment by bfranceschiello** [comment]
I don’t remember what it refers to in the manual, but I assume yes Il giorno 20 ott 2023, alle ore 13:20, esavary ***@***.***> ha scritto:﻿
In the parameters, we must select the type of eye-tracker: EYELINK 1000 LONG RANGE, TOWER, DESKTOP, or REMOTE. @bfranceschiello is correct to use LONG RANGE?

**Comment by oesteban** [comment]
Just checked the manual - as per figure 1.6, yes, this is the LONG RANGE setup.
