### ISSUE TITLE
Food for thoughts based on yesterday's last piloting session

### ISSUE THREAD

**Issue by helenelajous** [TheAxonLab/hcph-sops#274]
Yesterday, we ran the "HCPh_LR" protocol. Since the real acquisitions will start tonight, I decided to gather all my comments/suggestions here instead of opening up a new issue for each of them. I let you decide what would be worth it and feasible to still include and account for in the final protocol.

### T1 MPRAGE:
- The adjustment volume is huge: it should be reduced (I would say to match the FoV).
- The FoV cuts the nose (might be problematic in the AP/PA protocols): I think we never had this issue, but I would recommend, as a general and good practice, to always check the images you acquired in order to be sure they are not corrupted (be especially careful of wrap-around artifacts in that case).

### DWI & fMRI:
- Since the MPRAGE is now transverse, the FoV of the DWI and fMRI sequences should now be positioned on the scout (instead of the HR MPRAGE as before). Think about using the interpolated sagittal image (labeled as "1" in the scout) and not the few, thick slices ("2"). @esavary is aware.

### DWI:
- @oesteban: You may want to double-check the file used to define the directions of the diffusion vectors (see: Diff - Diffusion mode: Free - Import). The current file "multishell_hcph.dvs" (from February 2023) only allows 279 directions. However, you asked me to show Elodie and Alex how to make this sequence faster with only half of the directions in case you're running out of time. I had to import a more recent "multishell_hcph_actual.dvs" file (from May 2023) that allows to reduce the number of directions to 140 (only 2 options though: 6 or 140). I showed this procedure to @acionca, but you may want to double-check the files (I'm surprised we have to import another .dvs file instead of simply changing the number of directions from a single .dvs file).
- Also, you may want to double-check the quality of the images we acquired with the reduced FoVPhase (71%) as suggested by Jean-Baptiste (it was mentioned in #198 but not clear whether you had already implemented it).

### Checklist:
Back in June, we defined with @celprov and @esavary a short checklist of reminders that was supposed to come besides the SOPs (e.g., to be sure we think of unchecking the derivatives of the DWI sequence before running it). I don't know whether these comments were finally included in the SOPs, but that would be good to double-check.

### Suggestions:
I was able to run the field maps from the "HCPh_LR" protocol. Besides, and although #194 was marked as "won't fix", I worked on increasing the spatial resolution of the field maps. I saved two options at the end of the "20231019-Piloting_HCPh_LR" protocol (which corresponds to the one I ran yesterday):
- "field_map_HR": 1.3-mm isotropic field map (TR: 4,800 ms; number of slice: 105; FoVRead: 228 mm; FoVPhase: 73.6%; slice thickness: 1.3 mm; BaseResolution: 174 voxels; bandwidth: 1690 Hz/Px)
- "field_map_HR1_2mm_BW": 1.2-mm isotropic field map with a reduced bandwidth (TR: 5,300 ms; number of slice: 114; FoVRead: 228 mm; FoVPhase: 73.7%; slice thickness: 1.2 mm; BaseResolution: 190 voxels; bandwidth: 1462 Hz/Px)
@oesteban please have a look at the corresponding field maps if you're still interested in leveraging the longer TR of these acquisitions to increase the spatial resolution (the "field_map_HR" was acquired as the 7. scan of yesterday's session, and the "field_map_HR1_2mm_BW" as the 21. scan) -- I don't know if such field maps would suit your expectations.

**Comment by oesteban** [comment]
> ### T1 MPRAGE:
> 
>     * The adjustment volume is huge: it should be reduced (I would say to match the FoV).

I have checked this and the volume is fine - it looks huge because of the tilt, but there's nothing we need to operate here. Thanks for writing down and making sure we're not making a mistake.

>     * The FoV cuts the nose (might be problematic in the AP/PA protocols): I think we never had this issue, but I would recommend, as a general and good practice, to always check the images you acquired in order to be sure they are not corrupted (be especially careful of wrap-around artifacts in that case).

@acionca @esavary I guess this is something we may want to try to avoid, but I would give it low priority. As long as the nose does not overlap the back of the head (and it doesn't), this should be okay. It's also less problematic as now the AP/PA is readout direction (therefore more bandwidth, less problems with aliases).
 
> ### DWI & fMRI:
> 
>     * Since the MPRAGE is now transverse, the FoV of the DWI and fMRI sequences should now be positioned on the scout (instead of the HR MPRAGE as before). Think about using the interpolated sagittal image (labeled as "1" in the scout) and not the few, thick slices ("2"). @esavary is aware.

Thanks - already doing this :)


> ### DWI:
> 
>     * @oesteban: You may want to double-check the file used to define the directions of the diffusion vectors (see: Diff - Diffusion mode: Free - Import). The current file "multishell_hcph.dvs" (from February 2023) only allows 279 directions. However, you asked me to show Elodie and Alex how to make this sequence faster with only half of the directions in case you're running out of time. I had to import a more recent "multishell_hcph_actual.dvs" file (from May 2023) that allows to reduce the number of directions to 140 (only 2 options though: 6 or 140). I showed this procedure to @acionca, but you may want to double-check the files (I'm surprised we have to import another .dvs file instead of simply changing the number of directions from a single .dvs file).

I checked and everything is fine, you made the right call at the time.

>     * Also, you may want to double-check the quality of the images we acquired with the reduced FoVPhase (71%) as suggested by Jean-Baptiste (it was mentioned in #198 but not clear whether you had already implemented it).

I will double-check on my computer, but they look good on the scanner's console.



> ### Checklist:
> 
> Back in June, we defined with @celprov and @esavary a short checklist of reminders that was supposed to come besides the SOPs (e.g., to be sure we think of unchecking the derivatives of the DWI sequence before running it). I don't know whether these comments were finally included in the SOPs, but that would be good to double-check.

Yes, those made it to the SOPs and were retained.



> * "field_map_HR": 1.3-mm isotropic field map (TR: 4,800 ms; number of slice: 105; FoVRead: 228 mm; FoVPhase: 73.6%; slice thickness: 1.3 mm; BaseResolution: 174 voxels; bandwidth: 1690 Hz/Px)

We finally stuck with these, I think they offer a great compromise with isotropic voxels - thanks for this!


Please reopen if there's something else we should action from here and I forgot. Thanks!
