### ISSUE TITLE
Syncbox reaching max number of triggers

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#281]
It appears the maximum number of triggers that can be tramitted by the syncbox is 9999 and we are reaching ~9800 trigger. This might be the cause of triggers not being sent during the second (back-to-back) session. We would need to reset the box between session to be safe.

**Comment by oesteban** [comment]
This makes ALL the sense.

Can you update the SOPs to indicate what things need to be restarted (I'm thinking the "Examination" at the scanner's console, and *AcqKnowledge* are two more) when running back-to-back sessions?
