### ISSUE TITLE
[TODAY] Discuss RB calibration

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#306]
I think asking the participant to unplug the RB (or coming in the room to unplug/plug it) is unnecessary. We could just detach te tube from the BIOPAC and reattach it after calibration - WDTY?

**Comment by acionca** [comment]
We could try it but it means potential tension/pressure on the RB tube will not be taken into account during the calibration - I am not sure how this could influence the overall signal. Let's try and if the signal looks bad, we can ask you to unplug-calibrate-plug between two sequences.

**Comment by oesteban** [comment]
Done!
