### ISSUE TITLE
Create a *psychopy* experiment with only ET calibration

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#307]
Here:

https://github.com/TheAxonLab/hcph-sops/blob/bd2dd5072c19acc1ef24caf41c6eabe78238f558/docs/data-collection/notes-et.md#L7

we indicate we use the QCT (although we are using the fixation task).

Either way, this generates output files that make identifying relevant files harder.

Let's create (or reuse the validation task) for the only purpose of the initial calibration of the ET. WDYT?

**Comment by esavary** [comment]
Yes, we can use the calibration task for this purpose (since the filename is already 'calibration' it would be a good idea).

**Comment by oesteban** [comment]
Reopening because:

- We will need to make sure it is up-to-date with the other tasks after the upgrade
- We also want to change the name, because it is called validation if I'm not mistaken.
