### ISSUE TITLE
QA/QC protocol for preprocessed data

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#348]
Transferring content from the Frontiers RT, write down how to use fMRIPrep/dMRIPRep to generate reports and assess the preprocessed data (including **exclusion criteria**).

**Comment by celprov** [comment]
PR #386 addresses this issue, but it is not yet complete.
Currently, explanation or exclusion criteria are missing for the following sections of the fMRIPrep report:

- [ ] Summary
- [ ] Anatomical conformation
- [ ] T2* map
- [ ] T2* GM values
- [ ] Variance explained by Compcor components

**Comment by oesteban** [comment]
Let's open at least one issue for these specific elements. Your comment
will be buried as closed when this is merged and that's not ideal. We can
close the new issue when #386 is merged.
