### ISSUE TITLE
Anatomical MRIQC reports missing for some sessions

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#374]
- [ ] ses-2
- [ ] ses-12
- [ ] ses-14

**Comment by oesteban** [comment]
These sessions are excluded and replaced with make up sessions (which have
index above 36)

**Comment by celprov** [comment]
ah ok!

**Comment by celprov** [comment]
@oesteban Is it normal that all sessions between 30 and 36 are missing?

**Comment by oesteban** [comment]
Yes. There's a table in the SOPs (participant prep) where sessions skipped
are marked with an x

**Comment by celprov** [comment]
Ok thanks
