### ISSUE TITLE
Exclude pilot session from anatomical workflow fMRIPrep

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#389]
I think I should exclude the pilot session from the fMRIPrep anatomical workflow, right? @oesteban

**Comment by oesteban** [comment]
Yes

**Comment by celprov** [comment]
How do I do that? "session": "ses-0*" is not accepted as a valid syntax in the filter json

**Comment by oesteban** [comment]
I believe you can write a regex:

"^0\d\d"

**Comment by celprov** [comment]
Nope both "0*" and "^0\d\d" lead to invalid syntax error in JSON. According to [this](https://github.com/bids-standard/pybids/blob/master/bids/layout/config/bids.json) we are only allowed alphanumeric characters in the session value.

But we can make a list of sessions !

**Comment by oesteban** [comment]
And '^0\\d\\d' ?

Please note the single quotes too
