### ISSUE TITLE
code/events/schedule.tsv contains errors

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#394]
The names in code/events/schedule.tsv should align with code/eyetracking/schedule.tsv in PR #383. For instance, for session 1, the DWI file should be fixation_2023-10-20_18h48.03.561_5_session_1.log instead of fixation_2023-10-20_18h46.06.106_4_session_1.log. I verified code/eyetracking/schedule.tsv while processing the eyetracker data yesterday. If this file was used to generate events files for all sessions, some may be corrupted.

**Comment by oesteban** [comment]
Can you send a PR fixing these?

**Comment by celprov** [comment]
I believe this has been closed by #395. Feel free to reopen if that's wrong.
