### ISSUE TITLE
Exclusion criteria missing for some fMRIPrep visual report sections

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#419]
Currently, explanation or exclusion criteria are missing for the following sections of the fMRIPrep report:

- [x] Summary
- [ ] ~Anatomical conformation~ now #441
- [ ] ~T2* map~ now #442 
- [ ] ~T2* GM values~ now #443 
- [x] Variance explained by Compcor components

**Comment by oesteban** [comment]
These were not covered with #386.

**Comment by celprov** [comment]
I'm closing this issue in favor of breaking each bullet point into a separate issue
