### ISSUE TITLE
Compile figures of the QC checkpoints on denoised data into an HTML report

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#439]
@oesteban using reports and a yml recipe, this should not take too much time, right?

The three plots generated for QA need to be considered simultaneously so they will be more conveniently visualized if all plotted in the same document.

**Comment by oesteban** [comment]
> @oesteban using reports and a yml recipe, this should not take too much time, right?

That would be the gist of nireports :)
