### ISSUE TITLE
Write down QC protocol

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#78]
Perhaps start bringing content from the Frontiers RT?

From https://github.com/TheAxonLab/hcph-sops/issues/78#issuecomment-1730325376 below:

- [ ] Write down MRIQC's QC exclusion criteria
- [ ] Write down fMRIPrep's QC exclusion criteria
- [ ] Write formal QC procedure
- [ ] Write physio QC procedures and criteria (from #191)

**Comment by celprov** [comment]
- [ ] Write down MRIQC's QC exclusion criteria
- [ ] Write down fMRIPrep's QC exclusion criteria
- [ ] Write formal QC procedure

**Comment by oesteban** [comment]
Let's start with MRIQC's for/around ISMRM deadline the day after tomorrow.

**Comment by oesteban** [comment]
Closing in favor of more specific issues: #347, #348, and #349.
