### ISSUE TITLE
A ``[INSERT PICTURE]`` tag is remaining in emergency procedures section

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#89]
Here:

https://github.com/TheAxonLab/hcph-sops/blob/5c88791e061a2d9f9c75a6931f1afefcbfce08fd/docs/data-collection/emergency-procedures.md#L89

**Comment by acionca** [comment]
Two similar tags are also in pre-session.md (see below).
https://github.com/TheAxonLab/hcph-sops/blob/bd77127203d406d9382316f9bde856ac280d2df4/docs/data-collection/pre-session.md?plain=1#L133-L134

**Comment by acionca** [comment]
> Two similar tags are also in pre-session.md (see below).
> 
> https://github.com/TheAxonLab/hcph-sops/blob/bd77127203d406d9382316f9bde856ac280d2df4/docs/data-collection/pre-session.md?plain=1#L133-L134

I believe the PR did not fix these [INSERT PICTURE] and [TOCHECK] tags (originally mentioned in #139).

**Comment by oesteban** [comment]
Correct, that's why #139 should remain open :)
